version: '3'
services:
  accounting-app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: accounting-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
